import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ModalController from "@/components/common/modal/ModalController";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalController/>
      <body>{children}</body>
    </html>
  );
}
