import type { Metadata } from "next";
import "./globals.css";
import ModalController from "@/components/common/modal/ModalController";
import Header from "@/components/common/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ModalController/>
        <Header />
        {children}
      </body>
    </html>
  );
}
